apiVersion: v1
kind: Service
metadata:
  name: {{ include "shipping-service.fullname" . }}
  labels:
    {{- include "shipping-service.labels" . | indent 4 }}
  {{- with (include "shipping-service.metadataAnnotations" . | trim) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "shipping-service.selectorLabels" . | nindent 4 }}
