{{- $configSum := include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shipping-service.fullname" . }}
  labels:
    {{- include "shipping-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "shipping-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "shipping-service.labels" . | nindent 8 }}
      annotations:
        checksum/config: {{ $configSum }}
        {{- range $k, $v := .Values.podAnnotations }}
        {{ $k | quote }}: {{ $v | quote }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- include "shipping-service.podSecurityContext" . | nindent 8 }}
      containers:
        - name: {{ include "shipping-service.name" . }}
          image: {{ include "shipping-service.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- include "shipping-service.containerSecurityContext" . | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "shipping-service.fullname" . }}
          env:
            {{- include "shipping-service.env" . | nindent 12 }}
          startupProbe:
            httpGet:
              path: {{ .Values.probes.startup.path }}
              port: http
            failureThreshold: {{ .Values.probes.startup.failureThreshold }}
            periodSeconds: {{ .Values.probes.startup.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: http
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: http
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
