apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  SERVICE_NAME: "{{ .Release.Name }}-{{ .Chart.Name }}"
  SERVICE_VERSION: {{ .Chart.AppVersion | quote }}
  DEPLOY_ENV: {{ .Values.config.environment | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  SHIPPING_DEFAULT_CARRIER: {{ .Values.config.defaultCarrier | quote }}
  SHIPPING_STORAGE: {{ .Values.config.storage | quote }}
