{{- $configSum := include (print $.Template.BasePath "/configmap.yaml") . | sha256sum -}}
{{- include "pc-lib.deployment" (dict
    "root" .
    "env" (include "shipping-service.env" .)
    "envFrom" (printf "- configMapRef:\n    name: %s" (include "pc-lib.fullname" .))
    "podAnnotations" (dict "checksum/config" $configSum)) }}
