apiVersion: v1
kind: Service
metadata:
  name: shipping-service
  labels:
    app.kubernetes.io/name: shipping-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
      nodePort: 30080
  selector:
    app.kubernetes.io/name: shipping-service
